name = "LabPressureController"
uuid = "e62b489e-55c2-4f7e-b08d-c50d8555046d"
authors = ["Jan Kuhfeld <jan@kuhfeld.net> and contributors"]
version = "1.0.0-DEV"

[weakdeps]
Bonito = "824d6782-a2ef-11e9-3a09-e5662e0c26f8"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[extensions]
LiveViewExt = ["WGLMakie", "Bonito"]

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
